[application]
    name = "taurus manager"
    owner = "yann"

[log]
    # log level  0 - 6
    Level = 6

# Web层配置
[web]
    # 默认https
    proto = "http"
    # ip address, 默认监听的是内网IPv4的8901端口
    address = "0.0.0.0:8002"
    # 对应的私钥文件位置
    keypath = "/Users/yann/Desktop/chat-netpool/src/yann-chat/resource/key.pem"

[dao]
    # mysql
#    [dao.mysql]
#        DSNAPP = "root:123456@tcp(192.168.1.200:3306)/taurus_torent?charset=utf8mb4"
#        DSNADMIN = "root:123456@tcp(192.168.1.200:3306)/torent_admin?charset=utf8mb4"
#        Debug = true  #true为全局打印sql
#        MaxIdleConns = 10   #最大闲置连接数
#        MaxOpenConns = 100  #最大连接数
#        MaxConnMaxLifetime = 3000 #设置链接可以重用时长
    # redis
    [dao.redis]
        Addr = "127.0.0.1:6379"
        Size = 10          #redis 连接池大小

[snowflake]  #雪花算法 通过区分业务id或者机器id 生成唯一id
    WorkerId = 1   # 1-31  机器id
    DatacenterId = 1 # 1-31 业务id
[manager]
    MaxConnect = 1024  #单机最大连接数可通过设置系统进程最大打开文件符数量

[mq]
    AmqpAddr="amqp://yann:asd12300@127.0.0.1:5672/"  #rabbitmq addr
    ExchangeName="chicha:fanout:chat:message"    #交换机名称